#!/bin/bash
export ma_vendorId=phpsdk
export ma_vendorPassword=eZytH7Psjb
export ma_userId=phpsdkuser
export ma_userPassword=mAQ7xAha
export ma_userToken=C6YjOGeIU9kswEpupXC5u97I/eQLAzPPV/YWqVL6tSykx5Gn6TMFr993YVbF5B04
export ma_propertyId=4304
export ma_PMSUserId=240

export ma_userId2=phpsdkuser2
export ma_userPassword2=pr3fesWe

export ma_userId3=phpsdkuser3
export ma_userPassword3=password

export ma_userId4=phpsdkuser4
export ma_userPassword4=password

export ma_userId5=phpsdkuser5
export ma_userPassword5=password

export ma_userId6=phpsdkuser6
export ma_userPassword6=password

# 7 8 

# Unused - just for my records
# export ma_userEmail=nathan.helenihi@cloudbeds.com
# export ma_userCustomerEmail=nathan.helenihi@cloudbeds.com
# export ma_userEmail2=nhelenih@gmail.com
# export ma_userCustomerEmail2=nhelenih@gmail.com
